DROP SEQUENCE SEQ_TEST_EXISTS;
DROP TABLE TEST_EXISTS;

CREATE SEQUENCE SEQ_TEST_EXISTS  	-- SEQ_TEST_EXISTS 라는 시퀀스 객체 생성
START WITH 1  			-- 시작 번호는 1부터
INCREMENT BY 1			-- 1씩 증가
MAXVALUE 100000			-- 최대 100000까지
NOCYCLE				-- 100 이후에는 증가하지 않고 에러발생 알림
NOCACHE;			-- 캐쉬 사용 안함


CREATE TABLE TEST_EXISTS
(
    EX_ID    NUMBER
);

DECLARE 
NUM NUMBER :=1;

BEGIN
    LOOP
    INSERT INTO TEST_EXISTS  VALUES(SEQ_TEST_EXISTS.NEXTVAL);
    NUM := NUM+1;
    EXIT WHEN NUM > 100000;
    END LOOP;
END;






