SELECT * FROM EMPLOYEE;

--IS NULL / IS NOT NULL 연산자
SELECT EMP_NAME, MANAGER_ID, DEPT_CODE FROM EMPLOYEE WHERE DEPT_CODE IS NULL AND MANAGER_ID IS NULL;
SELECT * FROM EMPLOYEE WHERE DEPT_CODE IS NULL AND BONUS IS NOT NULL;

--IN / NOT IN 연산자
SELECT * FROM EMPLOYEE WHERE DEPT_CODE IN('D6', 'D9');

--연산자 우선순위
SELECT EMP_NAME, SALARY, JOB_CODE FROM EMPLOYEE WHERE JOB_CODE IN ('J2', 'J7') AND SALARY > 2000000;

SELECT EMP_NAME, EMP_NO, DEPT_CODE FROM EMPLOYEE WHERE DEPT_CODE IN ('D1', 'D2', 'D6') ORDER BY DEPT_CODE DESC;

--실습4 문제1번
SELECT EMP_NAME, EMP_NO, SALARY, HIRE_DATE FROM EMPLOYEE
WHERE (SYSDATE-HIRE_DATE)/365 BETWEEN 5 AND 10;

--실습4 문제2번
SELECT EMP_NAME, DEPT_CODE, HIRE_DATE, round(SYSDATE-HIRE_DATE)||'일' AS 근무기간, ENT_DATE
FROM EMPLOYEE WHERE ENT_YN = 'Y';

--실습4 문제3번
SELECT EMP_NAME, SALARY+(SALARY*0.5) AS "인상 급여", FLOOR((SYSDATE-HIRE_DATE)/365) AS 근속년수
FROM EMPLOYEE
WHERE (SYSDATE-HIRE_DATE)/365 >= 10
ORDER BY 근속년수 ASC;

--실습4 문제4번
SELECT EMP_NAME, EMP_NO, EMAIL, PHONE, SALARY FROM EMPLOYEE
WHERE (HIRE_DATE BETWEEN '99/01/01' AND '10/01/01') AND SALARY <= 2000000;


--실습4 문제5번
SELECT EMP_NAME, EMP_NO, SALARY, NVL(DEPT_CODE,'없음') AS DEPT_CODE 
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000000 AND 3000000
AND SUBSTR(EMP_NO,8,1) = '2' 
AND SUBSTR(EMP_NO,4,1) = '4'
ORDER BY EMP_NO DESC;

SELECT EMP_NAME, EMP_NO, SALARY, NVL(DEPT_CODE,'없음') AS DEPT_CODE 
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000000 AND 3000000
AND EMP_NO LIKE '__04__-2%'
ORDER BY EMP_NO DESC;

--실습4 문제6번
SELECT EMP_NAME, FLOOR((SYSDATE-HIRE_DATE)/1000)*(SALARY*0.1) AS "특별 보너스"
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,8,1) = '1' 
AND BONUS IS NULL
ORDER BY EMP_NAME ASC;

SELECT RTRIM(
LTRIM('982341678934509HELLO89798739273402' 
,'9876543210')
, '0123456789') AS STR FROM DUAL;

--EMPLOYEE테이블에서 이메일주소 중 아이디만 출력해라
SELECT RTRIM(RTRIM(EMAIL, 'kh.or.kr'),'@') FROM EMPLOYEE;

--EMPLOYEE테이블에서 사원들의 이름의 성을 중복 없이 사전순으로 출력해라
SELECT DISTINCT SUBSTR(EMP_NAME, 1,1) AS 성 FROM EMPLOYEE ORDER BY 성 ASC;

--EMPLOYEE테이블에서 남자만 사원번호, 사원명, 주민번호, 연봉을 출력하라
--단 주민번호 뒷자리의 뒤6자리는 *로 표시하라
SELECT EMP_ID, EMP_NAME, 
RPAD(RPAD(EMP_NO,8),14, '*'), SALARY*12 AS 연봉 
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,8,1) = 1;

--EMPLOYEE테이블의 모든 직원의 이름, 주민번호, EMAIL을 출력
--단, 출력시 EMAIL은 KH.OR.KR에서 IEI.OR.KR로 변경하여 출력하라
SELECT EMP_NAME, EMP_NO, 
REPLACE(EMAIL, 'kh.or.kr', 'iei.or.kr') AS Eamil 
FROM EMPLOYEE;

SELECT RPAD(ROUND(123.456,1),7,0) FROM DUAL;

SELECT FLOOR(123.45) FROM DUAL;

SELECT SYSDATE, CURRENT_DATE, LOCALTIMESTAMP, CURRENT_TIMESTAMP FROM DUAL;


SELECT EMP_NAME,
FLOOR(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS "근무 개월수" 
FROM EMPLOYEE 
ORDER BY "근무 개월수" DESC;

SELECT SYSDATE AS 현재날짜
, ADD_MONTHS(SYSDATE , 18) AS 전역일,
(ADD_MONTHS(SYSDATE , 18)-SYSDATE) *3 AS "먹어야할 짬밥"
FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '월') FROM DUAL;
SELECT LAST_DAY(TO_DATE('20/10/31')) FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;

--테이블에서 사원의 이름, 입사일 연차를 출력하여라
--단, 입사일은 YYYY년 M월 D일로 출력하도록 하여라
SELECT EMP_NAME,
EXTRACT(YEAR FROM SYSDATE)||'년'
||EXTRACT(MONTH FROM SYSDATE)||'월'
||EXTRACT(DAY FROM SYSDATE)||'일' AS 입사일, 
EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIRE_DATE) 
|| '년차' 
AS 년차
FROM EMPLOYEE ORDER BY 년차 ASC;

--입사일을 기점으로 다음달 1일부터 6개월을 계산하여 출력하라
--출력 시 입사일 기준으로 정렬하시오
SELECT EMP_NAME AS 이름, HIRE_DATE AS 입사일,
LAST_DAY(HIRE_DATE)+1 AS 기준일,
ADD_MONTHS((LAST_DAY(HIRE_DATE)+1),6) AS "기준일+6개월",
EXTRACT(MONTH FROM ADD_MONTHS((LAST_DAY(HIRE_DATE)+1),6))||'월' AS "지급되는 달"
FROM EMPLOYEE
ORDER BY HIRE_DATE ASC;

SELECT TO_CHAR(SALARY*12, '9,999,999,999.999') AS 연봉 FROM EMPLOYEE;