---------------------------VIEW 실습
--VIEW를 생성하기 위해선 권한이 있어야함
--SYSTEM계정으로 GRANT CREATE VIEW TO KH
CREATE VIEW EMP_VIEW AS
SELECT E.EMP_ID, E.EMP_NAME, E.DEPT_CODE,
D.DEPT_TITLE, E.SALARY*12 AS 연봉
FROM EMPLOYEE E JOIN DEPARTMENT D
ON E.DEPT_CODE = D.DEPT_ID;

SELECT * FROM EMP_VIEW;

DROP VIEW EMP_VIEW;
--TEST01 계정에서 VIEW를 조회하기 위해 SYSTEM계정으로 접속하여 권한을 부여한다.
--GRANT SELECT ON KH.EMP_VIEW TO TEST01;
---------------------------------------------------------------------

---------------------------SEQUENCE 실습
CREATE SEQUENCE KH_MEMBER_ID_SEQ 
START WITH 500
INCREMENT BY 10
MAXVALUE 10000
NOCYCLE
NOCACHE;                  

CREATE SEQUENCE KH_MEMBER_JOIN_COM_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 10000
NOCYCLE
NOCACHE;

CREATE TABLE KH_MEMBER(
MEMBER_ID NUMBER,
MEMBER_NAME VARCHAR2(20),
MEMBER_AGE NUMBER,
MEMBER_JOIN_COM NUMBER);

INSERT INTO KH_MEMBER
VALUES(KH_MEMBER_ID_SEQ .NEXTVAL, '홍길동', 20, KH_MEMBER_JOIN_COM_SEQ.NEXTVAL);
INSERT INTO KH_MEMBER
VALUES(KH_MEMBER_ID_SEQ .NEXTVAL, '김말똥', 30, KH_MEMBER_JOIN_COM_SEQ.NEXTVAL);
INSERT INTO KH_MEMBER
VALUES(KH_MEMBER_ID_SEQ .NEXTVAL, '고길똥', 40, KH_MEMBER_JOIN_COM_SEQ.NEXTVAL);
INSERT INTO KH_MEMBER
VALUES(KH_MEMBER_ID_SEQ .NEXTVAL, '똥똥똥', 50, KH_MEMBER_JOIN_COM_SEQ.NEXTVAL);
INSERT INTO KH_MEMBER
VALUES(KH_MEMBER_ID_SEQ .NEXTVAL, '유비', 99, KH_MEMBER_JOIN_COM_SEQ.NEXTVAL);

SELECT * FROM KH_MEMBER;

DROP SEQUENCE KH_MEMBER_ID_SEQ;
DROP SEQUENCE KH_MEMBER_JOIN_COM_SEQ;
DROP TABLE KH_MEMBER;
----------------------------------------------------------------------------

-----------------------INDEX실습
CREATE INDEX EMP_INDEX ON EMPLOYEE
    (EMP_ID, EMP_NAME, EMP_NO);
    -- 자주 사용하는 검색인경우 인덱스로 미리 설정
SELECT * FROM USER_IND_COLUMNS WHERE INDEX_NAME = 'EMP_INDEX';
    
SELECT EMP_ID, EMP_NAME, EMP_NO  FROM EMPLOYEE; -- F10 으로 확인
    
DROP INDEX EMP_INDEX;

SELECT EMP_ID, EMP_NAME, EMP_NO  FROM EMPLOYEE; -- F10 으로 확인
---------------------------------------------------------------

--------------------------------동의어(SYNONYM)
----비공개 동의어
CREATE SYNONYM EMP FOR EMPLOYEE;

SELECT * FROM EMP;

DROP SYNONYM EMP;

SELECT * FROM DEPT;