--DECODE 예시
SELECT EMP_NAME, EMP_NO, DECODE(SUBSTR(EMP_NO,8,1),1,'남',2,'여') AS 성별 FROM EMPLOYEE ORDER BY 성별 ASC;

--CASE 예시1
SELECT EMP_NAME, EMP_NO,
CASE
    WHEN SUBSTR(EMP_NO,8,1)=1 THEN '남성'
    WHEN SUBSTR(EMP_NO,8,1)=2 THEN '여성'
END AS 성별 FROM EMPLOYEE;

--CASE 예시2
SELECT EMP_NAME, EMP_NO,
CASE
    WHEN SUBSTR(EMP_NO, 1, 2) < 65 THEN '60년대 초반생'
    WHEN SUBSTR(EMP_NO, 1, 2) = 65 THEN '60년대 중반생'
    WHEN SUBSTR(EMP_NO, 1, 2) > 65 THEN '60년대 후반생'
END
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 1, 1) = 6;

--그룹함수 SUM 예시1
SELECT SUM(SALARY) AS "남자 사원 급여 총합" 
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 8, 1) = 1;

--그룹함수 SUM 예시2
SELECT SUM(SALARY*12)+SUM(SALARY*BONUS) AS "D5부서 급여 총합" 
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5';

--그룹함수 AVG 예시
SELECT AVG(SALARY)
FROM EMPLOYEE
WHERE EMP_NAME IN ('송종기', '선동일');

--그룹함수 AVG 예시2
SELECT ROUND(AVG(NVL(SALARY*BONUS,0)),1) AS 보너스평균 FROM EMPLOYEE;

--그룹함수 COUNT 예시
SELECT COUNT(*) AS "여사원 수" FROM EMPLOYEE WHERE SUBSTR(EMP_NO,8,1)=2;
SELECT COUNT(*) FROM EMPLOYEE WHERE BONUS IS NOT NULL;
SELECT COUNT(DISTINCT DEPT_CODE) AS 부서개수 FROM EMPLOYEE;

--FUNCTION 실습 1번
SELECT EMP_NAME AS 직원명,
EMAIL, LENGTH(EMAIL) AS 이메일길이 FROM EMPLOYEE;
--FUNCTION 실습 2번
SELECT EMP_NAME AS 이름,
RTRIM(RTRIM(EMAIL,'kh.or.kr'),'@') AS "이메일 아이디" 
FROM EMPLOYEE;
--FUNCTION 실습 3번
SELECT EMP_NAME AS 직원명,
SUBSTR(EMP_NO, 1, 2) AS 년생,
CONCAT(NVL(BONUS,0)*100,'%') AS 보너스율
FROM EMPLOYEE WHERE SUBSTR(EMP_NO, 1, 2) 
BETWEEN 60 AND 69;
--FUNCTION 실습 4번
SELECT COUNT(PHONE)||'명' AS 인원 FROM EMPLOYEE 
WHERE SUBSTR(PHONE,1,3) NOT IN(010);
--FUNCTION 실습 5번
SELECT EMP_NAME AS 직원명,
EXTRACT(YEAR FROM HIRE_DATE)||'년'
|| EXTRACT(MONTH FROM HIRE_DATE)||'월'
AS 입사년월
FROM EMPLOYEE;
--FUNCTION 실습 6번
SELECT EMP_NAME, 
RPAD(SUBSTR(EMP_NO,1,8),14,'*') AS 주민번호
FROM EMPLOYEE;
--FUNCTION 실습 7번
SELECT EMP_NAME AS 이름,
JOB_CODE AS 직급코드,
TO_CHAR((SALARY*12) + NVL(SALARY*12*BONUS , 0),'L9,999,999,999') AS 연봉
FROM EMPLOYEE;
--FUNCTION 실습 8번
SELECT EMP_ID AS ID,
EMP_NAME AS 이름,
DEPT_CODE AS 부서코드,
HIRE_DATE AS 입사일 FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5', 'D9') AND
EXTRACT(YEAR FROM HIRE_DATE) = 2004;
--FUNCTION 실습 9번
SELECT EMP_NAME AS 이름,
HIRE_DATE AS 입사일,
FLOOR(SYSDATE-HIRE_DATE)||'일' AS 근무일수
FROM EMPLOYEE;
--FUNCTION 실습 10번
SELECT 
MAX(EXTRACT(YEAR FROM SYSDATE)-
CONCAT(DECODE(SUBSTR(EMP_NO,8,1),'1', '19','2','19','20'),
SUBSTR(EMP_NO,1,2))) AS "최대 나이",
MIN(EXTRACT(YEAR FROM SYSDATE)-
CONCAT(DECODE(SUBSTR(EMP_NO,8,1),'1', '19','2','19','20'),
SUBSTR(EMP_NO,1,2))) AS "최소 나이"
FROM EMPLOYEE;
--FUNCTION 실습 11번
SELECT EMP_NAME AS 이름,
NVL(DEPT_CODE,'부서없음' )AS 부서코드,
CASE
    WHEN DEPT_CODE = 'D5' THEN '야근'
    WHEN DEPT_CODE = 'D6' THEN '야근'
    WHEN DEPT_CODE = 'D9' THEN '야근'
    ELSE '야근 없음'
END AS 야근유무 FROM EMPLOYEE
ORDER BY DEPT_CODE;