SELECT EMP_NAME AS 이름, BONUS AS 보너스율, '%' AS 단위 FROM EMPLOYEE;


--실습1번
--1번
SELECT JOB_NAME FROM JOB;
--2번
SELECT * FROM DEPARTMENT;
--3번
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE FROM EMPLOYEE;
--4번
SELECT HIRE_DATE, EMP_NAME, SALARY FROM EMPLOYEE;
--5번
SELECT EMP_NAME, SAL_LEVEL FROM EMPLOYEE WHERE SALARY >= 2500000;
--6번
SELECT EMP_NAME, PHONE FROM EMPLOYEE WHERE SALARY >= 3500000 AND JOB_CODE = 'J3';

--실습2번
--1번
SELECT EMP_NAME AS 이름, (SALARY*12) AS 연봉,(SALARY*12)+(SALARY*12*BONUS) AS "총 수령액(보너스포함)", ((SALARY*12)+(SALARY*12*BONUS))-((SALARY*12)*0.03) AS "실 수령액(보너스포함)" FROM EMPLOYEE;

--2번
SELECT EMP_NAME AS 이름, round(SYSDATE-HIRE_DATE) AS 근무일수, '일' AS 단위 FROM EMPLOYEE;

--3번
SELECT EMP_NAME AS 이름, SALARY AS 월급, BONUS AS 보너스율 FROM EMPLOYEE WHERE (SYSDATE-HIRE_DATE)/365 >=20;

SELECT EMP_NAME AS 이름, DEPT_CODE AS 부서코드 FROM EMPLOYEE WHERE DEPT_CODE <> 'D5' AND DEPT_CODE <> 'D6';
SELECT EMP_NAME AS 이름, DEPT_CODE AS 부서코드 FROM EMPLOYEE WHERE NOT (DEPT_CODE = 'D5' OR DEPT_CODE = 'D6');
SELECT EMP_NAME AS 이름, DEPT_CODE AS 부서코드 FROM EMPLOYEE WHERE 'D5' NOT IN(DEPT_CODE) AND 'D6' NOT IN(DEPT_CODE);

SELECT EMP_NAME || '님' as 이름, SALARY || '원' as 월급 FROM EMPLOYEE;

SELECT EMP_NAME AS 이름, DEPT_CODE AS 부서코드, SALARY AS 월급 FROM EMPLOYEE WHERE SALARY BETWEEN 3500000 AND 6000000;

SELECT EMP_NAME AS 이름, HIRE_DATE AS 입사일 FROM EMPLOYEE WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/01/01' ORDER BY HIRE_DATE ASC;

SELECT EMP_NAME AS 이름, EMAIL FROM EMPLOYEE WHERE EMAIL LIKE '___#_%' ESCAPE '#';

SELECT EMP_NAME AS 이름 FROM EMPLOYEE WHERE EMP_NAME NOT LIKE '이%';

SELECT EMP_NAME AS 이름, EMAIL FROM EMPLOYEE WHERE EMAIL NOT LIKE '%n%' AND EMP_NAME NOT LIKE '김%' AND  EMP_NAME NOT LIKE '이%';

SELECT DEPT_CODE AS 부서코드, COUNT(*) AS 인원 , ROUND(AVG(SALARY)*12) AS 평균연봉 FROM EMPLOYEE GROUP BY DEPT_CODE ORDER BY 평균연봉 DESC;


