--ORACLE전용 구문
SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, 
EMPLOYEE.DEPT_CODE, DEPARTMENT.DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE EMPLOYEE.DEPT_CODE = DEPARTMENT.DEPT_ID
ORDER BY DEPT_CODE;

--ANSI 표준 구문
SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, 
EMPLOYEE.DEPT_CODE, DEPARTMENT.DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID) ORDER BY DEPT_CODE;

SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, 
EMPLOYEE.DEPT_CODE, DEPARTMENT.DEPT_TITLE,
EMPLOYEE.JOB_CODE, JOB.JOB_NAME
FROM EMPLOYEE, DEPARTMENT, JOB
WHERE EMPLOYEE.DEPT_CODE = DEPARTMENT.DEPT_ID
AND EMPLOYEE.JOB_CODE = JOB.JOB_CODE
ORDER BY DEPT_CODE;

--INNER JOIN
SELECT EMP_NAME AS 이름, DEPT_TITLE AS 부서,
JOB.JOB_NAME AS 직급, SALARY
FROM EMPLOYEE 
INNER JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
INNER JOIN JOB ON EMPLOYEE.JOB_CODE = JOB.JOB_CODE
ORDER BY 부서;

--LEFT OUTER JOIN
SELECT EMP_NAME AS 이름, DEPT_TITLE AS 부서,
JOB.JOB_NAME AS 직급, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
INNER JOIN JOB ON EMPLOYEE.JOB_CODE = JOB.JOB_CODE
ORDER BY 부서;

--RIGHT OUTER JOIN
SELECT EMP_NAME AS 이름, DEPT_TITLE AS 부서
FROM EMPLOYEE 
RIGHT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;

--FULL OUTER JOIN
SELECT EMP_NAME AS 이름, DEPT_TITLE AS 부서
FROM EMPLOYEE 
FULL JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID;

--SELF JOIN 예제
SELECT E1.EMP_ID AS "사원 ID", 
E1.EMP_NAME AS "사원 이름",
E1.MANAGER_ID AS "사원의 매니저ID", 
E2.EMP_ID AS "매니저의 ID",
E2.EMP_NAME AS "매니저의 이름" 
FROM EMPLOYEE E1 JOIN EMPLOYEE E2 ON E1.MANAGER_ID = E2.EMP_ID;

--SELF JOIN 실습
SELECT E1.EMP_ID, E1.EMP_NAME, '===>'
,E2.EMP_NAME, JOB.JOB_NAME, E2.SALARY
FROM EMPLOYEE E1 JOIN EMPLOYEE E2
ON E1.EMP_ID = E2.MANAGER_ID 
JOIN JOB ON E2.JOB_CODE = JOB.JOB_CODE
ORDER BY E1.EMP_ID ASC;

--다중 JOIN 예제
SELECT E.EMP_NAME, D.DEPT_TITLE, 
L.NATIONAL_CODE, J.JOB_NAME
FROM EMPLOYEE E 
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
LEFT JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE;

--다중 JOIN 실습
SELECT E.EMP_NAME,
CASE
    WHEN SUBSTR(EMP_NO,8,1)=1 OR SUBSTR(EMP_NO,8,1)=2
    THEN (EXTRACT(YEAR FROM SYSDATE)-CONCAT(19, SUBSTR(EMP_NO,1,2)))+1
    ELSE (EXTRACT(YEAR FROM SYSDATE)-CONCAT(20, SUBSTR(EMP_NO,1,2)))+1
END AS 나이,
D.DEPT_TITLE, 
L.NATIONAL_CODE, J.JOB_NAME
FROM EMPLOYEE E 
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
LEFT JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE;

--실습
--급여가 350 ~ 600만원인 사람의 이름, 부서명, 직책명, 급여를 출력해라
--부서코드, 직책코드가 아닌 부서명, 직책명
--단, 부서가 없는 사람은 부서 없음 이라고 출력
--급여순으로 내림차순으로 출력
SELECT EMP_NAME AS 이름, 
NVL(DEPT_TITLE, '부서 없음') AS 부서,
JOB.JOB_NAME AS 직급, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
INNER JOIN JOB ON EMPLOYEE.JOB_CODE = JOB.JOB_CODE
WHERE SALARY BETWEEN 3500000 AND 6000000
ORDER BY SALARY DESC;