GRANT CREATE VIEW TO KHTEST;
GRANT CREATE SYNONYM TO KHTEST;

GRANT SELECT ON KH.EMP_VIEW TO TEST01;

GRANT SELECT ON KH.DEPARTMENT TO TEST01;

CREATE PUBLIC SYNONYM DEPT FOR KH.DEPARTMENT;
SELECT * FROM DEPT;

CREATE USER khtest identified by khtest;
GRANT CONNECT, RESOURCE TO KHTEST;

CREATE USER cns identified by cns;
GRANT RESOURCE, CONNECT TO cns;
---------------------------------------------------
CREATE USER ROLE_TEST IDENTIFIED BY ROLE_TEST;

CREATE ROLE emptyROLE;
CREATE ROLE connectROLE;
CREATE ROLE managerROLE;

GRANT CREATE SESSION TO connectROLE;
GRANT CREATE SESSION, CREATE TABLE TO managerROLE;
GRANT connectROLE TO ROLE_TEST;
GRANT managerROLE TO ROLE_TEST;
GRANT UNLIMITED TABLESPACE,CREATE SESSION, CREATE TABLE TO managerROLE;
REVOKE managerROLE FROM ROLE_TEST;
CREATE USER ROLE_TEST identified by ROLE_TEST;
commit;